# Generated by Django 5.0.6 on 2024-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='formato_especifico',
            field=models.BooleanField(verbose_name='Formato específico permite letras'),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='formato_geral',
            field=models.BooleanField(verbose_name='Formato geral permite letras'),
        ),
    ]
