# Generated by Django 5.0.6 on 2025-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0002_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='formato_especifico',
            field=models.BooleanField(blank=True, verbose_name='O formato específico permite letras?'),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='formato_geral',
            field=models.BooleanField(default=True, verbose_name='O formato geral permite letras?'),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='lista_severidade',
            field=models.CharField(max_length=200, verbose_name='Graus de severidade'),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='nomeclatura_espcifica',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomeclatura específica'),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='tipo_defeito',
            field=models.CharField(max_length=200, verbose_name='Tipos de defeito'),
        ),
    ]
