# Generated by Django 5.0.6 on 2024-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0002_alter_artefato_formato_especifico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='formato_especifico',
            field=models.BooleanField(verbose_name='Formato específico permite letras?'),
        ),
        migrations.AlterField(
            model_name='artefato',
            name='formato_geral',
            field=models.BooleanField(verbose_name='Formato geral permite letras?'),
        ),
    ]
