# Generated by Django 5.0.7 on 2024-07-18 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discrepancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancia_filtrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidade', models.CharField(max_length=50)),
                ('principal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='discrepancia.discrepancia', verbose_name='Discrepância principal')),
                ('repetidas', models.ManyToManyField(related_name='discrepancias_repetidas', to='discrepancia.discrepancia')),
            ],
            options={
                'verbose_name': 'Discrepância filtrada',
                'verbose_name_plural': 'Discrepâncias filtradas',
            },
        ),
    ]
