# Generated by Django 5.0.7 on 2024-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia_filtrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancia_filtrada',
            name='severidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
