# Generated by Django 5.0.6 on 2025-01-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia', '0004_alter_discrepancia_fonte_and_more'),
        ('discrepancia_filtrada', '0003_alter_discrepancia_filtrada_repetidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancia_filtrada',
            name='principal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='discrepancia.discrepancia', verbose_name='Discrepância principal'),
        ),
    ]
