# Generated by Django 5.0.7 on 2024-07-16 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0002_alter_inspecao_options'),
        ('inspetor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspetor',
            name='inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspecao.inspecao', verbose_name='Inspeção'),
        ),
        migrations.AlterField(
            model_name='inspetor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
