# Generated by Django 5.0.7 on 2024-08-05 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discrepancia', '0001_initial'),
        ('inspecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancia',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspecao.inspecao'),
        ),
    ]
