# Generated by Django 5.0.6 on 2024-08-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discrepancia',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='discrepancia',
            name='localizacao_especifica',
            field=models.CharField(default=0, max_length=5, verbose_name='Localização Específica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discrepancia',
            name='localizacao_geral',
            field=models.CharField(default=0, max_length=5, verbose_name='Localização Geral'),
            preserve_default=False,
        ),
    ]
