# Generated by Django 5.0.6 on 2025-01-13 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia', '0003_initial'),
        ('inspecao', '0007_alter_inspecao_finished_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancia',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecao.inspecao'),
        ),
        migrations.AlterField(
            model_name='discrepancia',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
