# Generated by Django 5.0.6 on 2025-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia', '0004_alter_discrepancia_fonte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancia',
            name='localizacao_especifica',
            field=models.CharField(max_length=20, verbose_name='Localização Específica'),
        ),
        migrations.AlterField(
            model_name='discrepancia',
            name='localizacao_geral',
            field=models.CharField(max_length=20, verbose_name='Localização Geral'),
        ),
    ]
