# Generated by Django 5.0.6 on 2025-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia', '0005_alter_discrepancia_localizacao_especifica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancia',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
