# Generated by Django 5.0.6 on 2025-01-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancia', '0006_alter_discrepancia_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancia',
            name='descricao',
            field=models.CharField(max_length=160, verbose_name='Descrição'),
        ),
    ]
