# Generated by Django 5.0.7 on 2024-07-18 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artefato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('link', models.URLField()),
                ('data_limite', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('artefato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='artefato.artefato')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
            },
        ),
    ]
