# Generated by Django 5.0.7 on 2024-07-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecao',
            options={'verbose_name': 'Inspeção', 'verbose_name_plural': 'Inspeções'},
        ),
    ]
