# Generated by Django 5.0.7 on 2024-08-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
