# Generated by Django 5.0.6 on 2024-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspecao',
            old_name='finalizada',
            new_name='deteccao_finalizada',
        ),
        migrations.AddField(
            model_name='inspecao',
            name='inspecao_finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
