# Generated by Django 5.0.6 on 2024-08-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefato', '0003_alter_artefato_formato_especifico_and_more'),
        ('inspecao', '0003_inspecao_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='artefato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artefato.artefato'),
        ),
    ]
