# Generated by Django 5.0.6 on 2024-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0003_rename_finalizada_inspecao_deteccao_finalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='inspecao_cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
