# Generated by Django 5.0.6 on 2024-10-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0004_inspecao_inspecao_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
