# Generated by Django 5.0.6 on 2024-10-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0005_inspecao_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='colecao_finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
