# Generated by Django 5.0.6 on 2025-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0006_inspecao_colecao_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
