# Generated by Django 5.0.6 on 2025-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0013_alter_inspecao_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecao',
            name='deteccao_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
