# Generated by Django 5.0.6 on 2025-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0014_inspecao_deteccao_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
