# Generated by Django 5.0.6 on 2025-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao', '0015_alter_inspecao_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspecao',
            old_name='deteccao_finished_at',
            new_name='deteccao_finalizada_at',
        ),
        migrations.RenameField(
            model_name='inspecao',
            old_name='finished_at',
            new_name='inspecao_finalizada_at',
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='data_limite',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
